---
Standards:
  -
    Title: "Managing Packages"
    Description: "Packages and Managing Packages, Virtual Environments"
    UID: 1e053af0-420f-48d6-bcbd-b3edbb822879
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: abirop
        Path: /managing-packages/packages-and-managing-packages.md
      -
        Type: Lesson
        UID: UZp4J5
        Path: /managing-packages/virtual-environments-and-projects.md
  -
    Title: Using The Debugger
    Description: "Intro to Debuggers, VS Code Debugging, Debugging Pytest, Problem Set: Using Debugger"
    UID: eb702636-a782-4ed3-8fb5-daca0aea5206
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 26f0b589-cb0f-4539-a4a6-1cb64f9ee28b
        Path: /intermediate-python-debugging/intro-to-debuggers.md
      -
        Type: Lesson
        UID: 506303a8-2fab-4283-98b3-9b4576721620
        Path: /intermediate-python-debugging/debugging-with-vs-code.md
      -
        Type: Lesson
        UID: 0cf83e0c-4483-4a15-8713-f35c425a16e1
        Path: /intermediate-python-debugging/debugging-with-pytest.md
      -
        Type: Lesson
        UID: a8e761cc-0d1f-49f9-a80a-6d2f79579a04
        Path: /intermediate-python-debugging/problem-set-using-the-debugger.md
  -
    Title: Collaborating with Git
    Description: "Collaborating, Reviewing Git History, Git Cheatsheet, Problem Set: Git Commands"
    UID: DaSCfO
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: wGkqyQ
        Path: /intro-to-git/collaborating.md
      -
        Type: Lesson
        UID: w3WLGs
        Path: /intro-to-git/reviewing-git-history.md
      -
        Type: Lesson
        UID: ce6c935d-a665-420e-97ba-8b4a5cebf4d7
        Path: /intro-to-git/git-cheatsheet.md
      -
        Type: Lesson
        UID: g1zQGU
        Path: /intro-to-git/problem-set-git-commands.md
  -
    Title: Branches In Git
    Description: "Branches, Using Branches in Git, Problem Set: Git, Activity: Merge Carnival"
    UID: 76a4001e9bc2734c2e93ede4b8f1297e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 6c8aa01cc55f51f3cb90f1fd9f851595
        Path: /branches-in-git/branches.md
      -
        Type: Lesson
        UID: f88500a61648d8752735ca1b0b3e9522
        Path: /branches-in-git/using-branches-in-git.md
      -
        Type: Lesson
        UID: a23c8692ae7b601177cd574151717d51
        Path: /branches-in-git/problem-set-git.md
      -
        Type: Lesson
        UID: 7166c21e-45ef-4189-bf0f-4f78a44fbab5
        Path: /branches-in-git/git-branching-merge-carnival.md
  -
    Title: "Code Reviews"
    Description: "Code Reviews, Github Pull Requests, Activity: Code Reviews"
    UID: 5ca5a675-2ca5-4d91-a610-260f17608bfe
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 64a8baf6-8bc7-49e1-ab8c-ff476e9b6e33
        Path: /github-code-reviews/code-reviews.md
      -
        Type: Lesson
        UID: 86b89d4a-1339-4ff5-bce6-8d6590c079be
        Path: /github-code-reviews/github-code-reviews.md
      # -
      #   Type: Lesson
      #   UID: bd734793-2da2-43db-986b-bf51c6c23ba6
      #   Path: /github-code-reviews/activity-code-reviews.md
  -
    Title: "External Resources"
    Description: "Learning Resources Provided by the Ada Community"
    UID: 19d7c672-ae13-407d-9cf2-d0615e75a726
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: b928006a
        Path: /resources/external-resources.md
